### PR TITLE
Bug fix in AlgoSiPM.cxx

### PR DESCRIPTION
**Pull request by Pabce**
Fixed the bug reported at: https://cdcvs.fnal.gov/redmine/issues/27944?issue_count=187&issue_position=1&next_issue_id=27933

### CODE REVIEW

**Review by knoepfel — COMMENTED** [review]
Thanks, @Pabce. I suggest that you just remove the code you commented out, and then give the git commit a descriptive message like "Account for all peaks above threshold."

**Comment by lgarren** [comment]
trigger build

**Comment by lgarren** [comment]
@LArSoft/level-2-managers  Requesting approval of this PR

**Comment by lgarren** [comment]
@LArSoft/level-2-managers  Do you approve this PR?

**Comment by lgarren** [comment]
Hello @LArSoft/level-2-managers  do you approve this PR?

**Comment by lgarren** [comment]
approve

**Pull request merged**
