### PR TITLE
PhotonInf_module.cc bug fixed, PhotonInf module will work normally after the modification.

### PR DESCRIPTION
**Pull request by szhang17phys**

### CODE REVIEW

**Review by knoepfel — COMMENTED** [review]
Looks fine.  I think the check probably isn't necessary at all (if `*ph_handle` is empty, then the statement below the `for` loop won't be executed).  However, I don't think you need to worry about fixing that here.

**Comment by lgarren** [comment]
trigger build

**Comment by lgarren** [comment]
approve

**Comment by lgarren** [comment]
+1

**Pull request merged**
