### PR TITLE
"larana

### PR DESCRIPTION
**Pull request by lgarren**

### CODE REVIEW

**Comment by lgarren** [comment]
code-checks

On 11/21/19 12:35 PM, Fermilab build bot account wrote:

A new Pull Request was created by @lgarren<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_lgarren&d=DwMFaQ&c=gRgGjJ3BkIsb5y6s49QqsA&r=P0Z7nIv69Nz5OP_L9NyELQ&m=TM3DZq-4aAob_sjZNBpVKUeYAIWW_1F09wht0CYiyYs&s=4d8M3vrJJo3wY4HM2EqOJHfmZDo1-_a9qfBgy6_yU_E&e=> (Lynn Garren) for develop.

It involves the following packages:

larana

@tomjunk<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_tomjunk&d=DwMFaQ&c=gRgGjJ3BkIsb5y6s49QqsA&r=P0Z7nIv69Nz5OP_L9NyELQ&m=TM3DZq-4aAob_sjZNBpVKUeYAIWW_1F09wht0CYiyYs&s=pagUItY-pn2_UUEe2jJEYYWK4rdFFJ7zpBXuESQP_l8&e=>, @knoepfel<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_knoepfel&d=DwMFaQ&c=gRgGjJ3BkIsb5y6s49QqsA&r=P0Z7nIv69Nz5OP_L9NyELQ&m=TM3DZq-4aAob_sjZNBpVKUeYAIWW_1F09wht0CYiyYs&s=Z8juIXwB1iDFIiNNu2d7XjmLLGs14jmTZPFn6PftOR8&e=>, @lgarren<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_lgarren&d=DwMFaQ&c=gRgGjJ3BkIsb5y6s49QqsA&r=P0Z7nIv69Nz5OP_L9NyELQ&m=TM3DZq-4aAob_sjZNBpVKUeYAIWW_1F09wht0CYiyYs&s=4d8M3vrJJo3wY4HM2EqOJHfmZDo1-_a9qfBgy6_yU_E&e=>, @gartung<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_gartung&d=DwMFaQ&c=gRgGjJ3BkIsb5y6s49QqsA&r=P0Z7nIv69Nz5OP_L9NyELQ&m=TM3DZq-4aAob_sjZNBpVKUeYAIWW_1F09wht0CYiyYs&s=JRv4jQJ2gPOnbQp5pLGT6bKytgyN3x7NSgImH_S_dGg&e=>, @FNALbuild<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_FNALbuild&d=DwMFaQ&c=gRgGjJ3BkIsb5y6s49QqsA&r=P0Z7nIv69Nz5OP_L9NyELQ&m=TM3DZq-4aAob_sjZNBpVKUeYAIWW_1F09wht0CYiyYs&s=67l356MsHdqi9_eJNf-Qpy1JI6dMjTMS-UEVXDQF_lA&e=>, @dladams<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_dladams&d=DwMFaQ&c=gRgGjJ3BkIsb5y6s49QqsA&r=P0Z7nIv69Nz5OP_L9NyELQ&m=TM3DZq-4aAob_sjZNBpVKUeYAIWW_1F09wht0CYiyYs&s=MmTA3pyhaBM2kGeWM0REavsnyp5bJtjRgQQw-9B3RMM&e=>, @erica-snider<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_erica-2Dsnider&d=DwMFaQ&c=gRgGjJ3BkIsb5y6s49QqsA&r=P0Z7nIv69Nz5OP_L9NyELQ&m=TM3DZq-4aAob_sjZNBpVKUeYAIWW_1F09wht0CYiyYs&s=6GkqlsM8qB7zndcgnSt9Y9ZZ_ETzEK1LV6lUzY3btBU&e=>, @yangtj207<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_yangtj207&d=DwMFaQ&c=gRgGjJ3BkIsb5y6s49QqsA&r=P0Z7nIv69Nz5OP_L9NyELQ&m=TM3DZq-4aAob_sjZNBpVKUeYAIWW_1F09wht0CYiyYs&s=GWVrxWb5f8gKwwUsfct8XL9mgRn37Vz8VVnOhFJ1Z2o&e=>, @SFBayLaser<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_SFBayLaser&d=DwMFaQ&c=gRgGjJ3BkIsb5y6s49QqsA&r=P0Z7nIv69Nz5OP_L9NyELQ&m=TM3DZq-4aAob_sjZNBpVKUeYAIWW_1F09wht0CYiyYs&s=R9UU4nU3s9w_HrHL5_0-OY_mmzh6tooKinEIZOgKK1M&e=>, @chalt007<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_chalt007&d=DwMFaQ&c=gRgGjJ3BkIsb5y6s49QqsA&r=P0Z7nIv69Nz5OP_L9NyELQ&m=TM3DZq-4aAob_sjZNBpVKUeYAIWW_1F09wht0CYiyYs&s=XeDHUrwyHfFF31pNFj00JiMv6q79lczHv3XcLYsG9iY&e=>, @vitodb<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_vitodb&d=DwMFaQ&c=gRgGjJ3BkIsb5y6s49QqsA&r=P0Z7nIv69Nz5OP_L9NyELQ&m=TM3DZq-4aAob_sjZNBpVKUeYAIWW_1F09wht0CYiyYs&s=h9sIuLSdXMuOhRq6xQUQGiwi52ckAkRFckArJ2XUi7c&e=>, @chissg<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_chissg&d=DwMFaQ&c=gRgGjJ3BkIsb5y6s49QqsA&r=P0Z7nIv69Nz5OP_L9NyELQ&m=TM3DZq-4aAob_sjZNBpVKUeYAIWW_1F09wht0CYiyYs&s=1IdTVcTOtRi71Ev0YbhxbN6Ke-nc4culSY-A_VudEqU&e=>, @hgreenlee<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_hgreenlee&d=DwMFaQ&c=gRgGjJ3BkIsb5y6s49QqsA&r=P0Z7nIv69Nz5OP_L9NyELQ&m=TM3DZq-4aAob_sjZNBpVKUeYAIWW_1F09wht0CYiyYs&s=MGPRKEoFfMy1JhwO72H7VSFDHOhK-xP-q7qA4KuthLk&e=> can you please review it and eventually sign? Thanks.
@gartung<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_gartung&d=DwMFaQ&c=gRgGjJ3BkIsb5y6s49QqsA&r=P0Z7nIv69Nz5OP_L9NyELQ&m=TM3DZq-4aAob_sjZNBpVKUeYAIWW_1F09wht0CYiyYs&s=JRv4jQJ2gPOnbQp5pLGT6bKytgyN3x7NSgImH_S_dGg&e=> this is something you requested to watch as well.

cms-bot commands are listed here<https://urldefense.proofpoint.com/v2/url?u=http-3A__cms-2Dsw.github.io_cms-2Dbot-2Dcmssw-2Dcmds.html&d=DwMFaQ&c=gRgGjJ3BkIsb5y6s49QqsA&r=P0Z7nIv69Nz5OP_L9NyELQ&m=TM3DZq-4aAob_sjZNBpVKUeYAIWW_1F09wht0CYiyYs&s=kecMytHCcPn1Y36q_AE6yFHDTn_y26JfWpM6VcGdwiE&e=>

**Comment by gartung** [comment]
@lgarren I will be removing comments from this PR to test changes to the cms-bot scripts which react based in previously posted comments.

**Comment by gartung** [comment]
approve

**Comment by gartung** [comment]
approve

**Comment by gartung** [comment]
approved

**Comment by gartung** [comment]
+1

**Comment by gartung** [comment]
+1

**Comment by gartung** [comment]
trigger build

**Comment by gartung** [comment]
approve

**Comment by gartung** [comment]
approved

**Comment by gartung** [comment]
+1

**Comment by gartung** [comment]
approve

**Comment by gartung** [comment]
merge

**Comment by gartung** [comment]
merge

**Pull request merged**
