### PR TITLE
MCC9 merge test build

### PR DESCRIPTION
**Pull request by hgreenlee**
Update ParticleID

### CODE REVIEW

**Comment by lgarren** [comment]
trigger build with with pull requests #15, LArSoft/lardataobj#17, LArSoft/larreco#35, LArSoft/lareventdisplay#13, LArSoft/lardata#20

**Comment by lgarren** [comment]
trigger build with pull requests #15, LArSoft/lardataobj#17, LArSoft/larreco#35, LArSoft/lareventdisplay#13, LArSoft/lardata#20

**Comment by lgarren** [comment]
tests need to be triggered by hand with provided experiment branches: greenlee_pid_update

**Comment by tomjunk** [comment]
Approved -- Herb says experiment code builds with his branches.

**Comment by lgarren** [comment]
approve

**Pull request merged**
